### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by antonk52** [mlaursen/coc-scssmodules#1]
Hi, I recently discovered your plugin and really like the idea. I have briefly played with it and wanted to share some feedback. The [parent selectors](https://sass-lang.com/documentation/style-rules/parent-selector) feature is not specific to sass/scss. It is also available for [stylus](https://stylus-lang.com/docs/selectors.html#parent-reference), [less](http://lesscss.org/features/#parent-selectors-feature) and as a [postcss plugin](https://github.com/postcss/postcss-nested).

Your plugin will work with any of the above(as long as the file extension matches). I am planning to add this functionality to `coc-cssmodules` since some people find it useful. Personally I do not use this feature since it makes it harder to grep the exact class name in the codebase. I will gladly accept any help or an advice on it.

Thanks for your plugin, amazing work! 👍

**Comment by mlaursen** [comment]
That's pretty exciting to hear! I haven't actually used stylus, less, or postcss (other than autoprefixer) so I didn't know parent selectors existed anywhere else. I've been meaning to open an issue in your project once I used this plugin a bit and tested it a bit more, but I found out I don't even use this since I'm too used to opening splits 😅 This ended up just being a way for me to learn a bit about creating a coc-extension.

Feel free to take anything that seems useful from this project and port into coc-cssmodules and I'll update this README to point to yours. Thanks for the feedback and the initial repo for me to reference when making this!

**Comment by antonk52** [comment]
Hi again, I've finally found time to implement the parent selectors as well as few other features which are now a part of coc-cssmodules [v1.1.0](https://github.com/antonk52/coc-cssmodules/releases/tag/v1.1.0). Hope will work great with the features you want🙂

**Comment by mlaursen** [comment]
Thanks a bunch! Seems to be working as expected. I'll close this issue once I've updated the README to say this package is deprecated and no longer needed after the `coc-cssmodules@v1.1.0` release.
