### ISSUE TITLE
sass files

### ISSUE THREAD

**Issue by ovidius72** [mlaursen/coc-scssmodules#2]
Does this module supports sass files. I found it very useful for scss files couldn't find a way to configure it to be used with the .sass extension.
Is it possible.
Thanks.

**Comment by mlaursen** [comment]
I'm not too familiar with the `sass` syntax, but I tried a few simple examples in my test file that seemed to work for both autocompletion and "Go to Definition" without any additional changes:

```sass
// test/HyphenatedBEM.module.sass
.container
  background-color: red

.clear
  clear: both

.something-amazing
  font-size: 1rem

.container-child
  width: 100%
```

using `"cssmodules.camelCase": true`

```diff
 import React from "react";
 
-import styles from "./HyphenatedBEM.module.scss";
+import styles from "./HyphenatedBEM.module.sass";
 
 const Test = () => (
   <div className={styles.container}>
     <div className={styles.clear}>Hello, world!</div>
   </div>
 );
 
 export default Test;
```

I might need to try a few more complex examples including mixins, selectors, and functions though.

Can you check what the output for `:set filetype?` is and paste it here? Also checking the log from `:CocOpenLog` might be helpful to see if there are any errors appearing.

**Comment by ovidius72** [comment]
Thank you.
I've tried in an empty sass file (:set filetype? is filetype=sass)
Syntax highlighting is ok but I get no autocompletion. 
In scss file it works as expected.
I also have coc-css installed and I've tried to disable it to avoid conflicts but it still doesn't work.
From the coc log these few lines are added from the moment I open the sass file and ad just one rule:
```
2020-10-26T17:46:40.349 INFO (pid:64674) [snippets-session] - Cursor insert out of range, cancelling snippet session
2020-10-26T17:46:41.903 INFO (pid:64674) [completion-complete] - Results from: buffer,emmet-sass
2020-10-26T17:46:43.853 INFO (pid:64674) [completion-complete] - Results from: buffer,emmet-sass
2020-10-26T17:46:46.795 INFO (pid:64674) [willSaveHandler] - Will save cost: 132
```

**Comment by mlaursen** [comment]
If I'm understanding correctly, this might be an issue with `coc-css` instead of this plugin if you are expecting autocompletion within a `.sass` file. This plugin (`coc-scssmodules`) really only provides autocompletion when you are in a javascript/typescript file and are using css modules. The autocompletion will suggest class names found in an imported `.sass`, `.scss`, or `.css` file or allow  you to go directly to that class from your javascript/typescript file.

`coc-css` should be the plugin that provides autocompletion within `.css`, `.sass`, `.scss`, and `.less` files for things such as existing variables, css properties, etc.

If I misunderstood, the last thing I can think of is that this plugin can only provide suggestions for saved files instead of open buffers. So if you have some changes in the `.sass` file that haven't been written yet, the suggestions might not appear in the javascript/typescript files.

**Comment by ovidius72** [comment]
Ok. I have to apologize because I misunderstood the scope of this plugin. I was expecting this plugin to work in .sass, .scss files but now I realized that I was completely wrong. So please do not take into account this issue. Sorry about that and thanks for your time.
